name: hts
description: A Hostel Booking and Tiffin service app

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  google_sign_in: ^4.4.4
  firebase_storage: ^3.1.5
  file_picker: any
  introduction_screen: any
  share: ^0.6.4
  flare_flutter: ^2.0.3
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_launcher_icons: ^0.7.5
  #Docs for flutter icons: https://github.com/fluttercommunity/flutter_launcher_icons
  #Run the following packages:
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    #For Images
    - assets/images/
    - assets/animations/
    - assets/data/